name = "PlutoCLI"
uuid = "7bac7b78-9528-45ef-8610-7ee14b3881e0"
authors = ["Roger-luo <rogerluo.rl18@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Comonicon = "863f3e99-da2a-4334-8734-de3dacbe5542"

[compat]
Comonicon = "0.5"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
